export const LOGIN_API_ENDPOINT = "login";
export const ROUTES_API_ENDPOINT = "admin/routes";
export const ROUTES_DROPDOWN_API_ENDPOINT = "admin/routes/dropdown";

export const USER_API_ENDPOINT = "admin/users";

export const VEHICLES_API_ENDPOINT = "admin/vehicles";
export const VEHICLES_DROPDOWN_API_ENDPOINT = "admin/vehicles/dropdown";
export const SEATS_API_ENDPOINT = "admin/seat";
export const VEHICLE_WISE_TOTAL_SEAT_REPORT_API_ENDPOINT =
  "admin/vehiclewisetotalseat";
export const VEHICLE_WISE_SEAT_API_ENDPOINT = "admin/vehiclewiseseat";
export const ADD_VEHICLE_BOOKING_FOR_TRIP_API_ENDPOINT =
  "admin/trip/vehicle/booking";
export const TRIPS_API_ENDPOINT = "admin/trip";
export const TRIP_SINGLE_API_ENDPOINT = "admin/single/trip";
export const TRIP_SUMMERY_API_ENDPOINT = "admin/tripsummery";
export const ACCOUNT_BALANCE_API_ENDPOINT = "admin/accountBalance";
export const ACCOUNT_HISTORY_API_ENDPOINT = "admin/accountHistory";
export const ADMIN_BOOKING_API_ENDPOINT = "admin/booking";
export const ADMIN_BOOKING_INVOICE_API_ENDPOINT = "admin/booking-invoice";
export const PACKAGE_API_ENDPOINT = "admin/packages";
export const SINGLE_PACKAGE_DETAILS = "packages";
export const REFUND_API_ENDPOINT = "admin/refund";
export const REFUND_DISBURSED_API_ENDPOINT = "admin/refund/disburse";
export const VEHICLE_API_ENDPOINT = "admin/useageOfVehicle";
export const GUIDE_API_ENDPOINT = "admin/guide";
export const TRIP_PERFORMANCE = "/admin/tripPerformance";
export const PACKAGE_PERFORMANCE = "/admin/packagePerformance";
export const CUSTOMER_VALUE_REPORT = "admin/customerValue";
export const HOTEL_API_ENDPOINT = "admin/hotel";
export const USER_HOTEL_API_ENDPOINT = "/hotel";
export const DASHBOARD = "admin/dashboard";
export const DASHBOARD_TABLE_VIEW = "admin/dashboard/databaseList";
export const MONTH_RUNNING_BALANCE = "admin/monthRunningBalance"
export const FINANCIAL_REPORT = "admin/financial_report"
export const TICKET_API_ENDPOINT = "admin/tickets";
export const TRANSACTION_API_ENDPOINT = "admin/transaction";
export const MONITORING_API_ENDPOINT = "admin/monitoring";
export const PACKAGE_SUMMARY_ENDPOINT = "admin/packageWiseBooking";
export const MENU_API_ENDPOINT = "admin/menu";
export const MENU_ITEMS_API_ENDPOINT = "admin/menu_items";
export const TRIPWISE_BOOKING_USERS_API_ENDPOINT = "admin/tripwiseBookingUsers";
export const ACCOUNT_HISTORY_SEARCH_API_ENDPOINT = "admin/account-history";
export const MONTHLY_DAILY_BALANCE_REPORT = "admin/monthlyDailyBalanceReport";
export const OVERALL_SALES_REPORT = "admin/overall-sales-summary";
export const ROUTE_WISE_SALES_REPORT = "admin/route-wise-sales-summary";
export const TICKET_STATUS_REPORT = "admin/ticket-status-report";
export const LOW_OCCUPANCY_TRIP_REPORT = "admin/low-occupancy-trip-report";
export const BLOG_API_ENDPOINT = "admin/blogs";
export const USER_GROWTH_REPORT = "admin/user-growth-report";